### ISSUE TITLE
[Feature Request] .appearance() support

### ISSUE THREAD

**Issue by undeaDD** [yervandsar/ExpandedTabBar#11]
UIKit like styling support for the UI elements.
i could open a PR, if wanted ^^

![479f1a13-e057-45fb-ad05-474f157c6965](https://user-images.githubusercontent.com/8116188/56159895-1a3ed700-5fc6-11e9-9857-c8efac2aebbd.jpeg)

**Comment by yervandsar** [comment]
Hi), we are open to your suggestions and will be happy with your contribution
