### ISSUE TITLE
Change Container Icon Color

### ISSUE THREAD

**Issue by goalguy10** [yervandsar/ExpandedTabBar#12]
How can we change the container icon color?

**Comment by yervandsar** [comment]
Now it is not available. I'll put it in next version.

**Comment by yervandsar** [comment]
@goalguy10 in new [2.0.1 version](https://github.com/yervandsar/ExpandedTabBar/tree/2.0.1) we have iconColor option in options.
It done in [bc78b68](https://github.com/yervandsar/ExpandedTabBar/commit/bc78b681c4d7446b3d0f5780666d4641db5185b4)

**Comment by yervandsar** [comment]
@goalguy10 have you more questions or can i close the issue
