### ISSUE TITLE
respect current UserInterfaceStyle ( dark and light mode )

### ISSUE THREAD

**Issue by undeaDD** [yervandsar/ExpandedTabBar#13]
simply change colors like .black or .white
to uicolors with two appearances (.systemBackground, .label)

**Comment by undeaDD** [comment]
also bottom constraint might be broken again ( not working on my iPhone xs with version 2.0.2 )

**Comment by undeaDD** [comment]
![Simulator Screen Shot - iPhone 11 - 2020-05-28 at 11 56 58](https://user-images.githubusercontent.com/8116188/83127365-5bb31880-a0da-11ea-8b6c-7af465e3bd46.png)

**Comment by yervandsar** [comment]
Will work in next version

**Comment by yervandsar** [comment]
@undeaDD you can see new major version(v3.0.0) [Branch](https://github.com/yervandsar/ExpandedTabBar/tree/swift-pm), it will come soon
