### ISSUE TITLE
List Items Horizontally in the Expanded Controller

### ISSUE THREAD

**Issue by emad3020** [yervandsar/ExpandedTabBar#4]
I need to know how to display items as horizontally stack like the items appeared in the tabBar itself

**Comment by yervandsar** [comment]
Hi @emad3020, Thanks a lot, at this moment we don't have horizontal stack in library

**Comment by emad3020** [comment]
I don't understand if that a problem or not ? if you have a problem please go in details so I . can help you solving it

**Comment by yervandsar** [comment]
@emad3020 No. There are no problems. You can't use ExpandedTabBar for displaying Horizontal stack for now.
